### ISSUE TITLE
Overflow & 0 doubloons until next bug

### ISSUE THREAD

**Issue by berke-volkan** [hackclub/high-seas#1015]
![IMG_20241222_113939.jpg](https://github.com/user-attachments/assets/f35dcdfa-6ef2-4066-91bf-50474193d2ef)

**Comment by Gitstar-OC** [comment]
The 0 doubloons is not a bug, I will try to solve that as there is no special case added for 0 doubloons and maybe the doubloons position will remain as it is (as it is absolute and not relative). Try using laptop / computer while on the high seas website as the website also lags (and uses a lot of memory ) on mobile due to very images assets and framer motion library!
