### ISSUE TITLE
Double raspberry pi in shop

### ISSUE THREAD

**Issue by Froppii** [hackclub/high-seas#801]
Happens when using the all across the seven seas option

**Comment by matytyma** [comment]
It's as it should be, it's due to shipping imo

**Comment by Froppii** [comment]
Hmm why though?

**Comment by matytyma** [comment]
They've had some raspis stocked at warehouse during arcade, so I'd guess it's leftover from then. The only problem with them is that they all had US PSUs.

**Comment by Froppii** [comment]
ahh I see, that makes sense

**Comment by transcental** [comment]
This is because they're technically different. One is US only (contains US power supplies), the other is for the rest of the world (doesn't have US power supply). It would be good if we could hide one of them on that page though, I imagine that would be fairly simple to add a toggle on Airtable - cc @24c02

**Comment by BudzioT** [comment]
#829  should handle that correctly
